
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gosgrymeknholdtnekcy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdvc2dyeW1la25ob2xkdG5la2N5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyNzAyNTIsImV4cCI6MjA1ODg0NjI1Mn0.bvxD5zZseYnPQc7rfC_yPzMXxGYru2BJvfih2aWcWKE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
